### ISSUE TITLE
Patterns do not seem to work in nginx

### ISSUE THREAD

**Issue by shoesforindustry** [getkirby-v2/patterns-plugin#33]
First the CSS and JS did not load [(see also this post...'Default styles not loading with php -S ... #31' )](https://github.com/getkirby/patterns/issues/31)

I can get the CSS and JS to load by manually adding the full path to the bottom of the lab file e.g.
Replace

``` php
//$theme->css = ... $this->url() . '/assets/dist/index.css';
//with
$theme->css = ... 'http://aap.dev/site/plugins/patterns/assets/dist/index.css'; etc..
```

But now the HTML and PHP buttons don't work in the interface.
A path or routing problem?

`[error] 2858#0: *593 open() "/Users/russellbaldwin/Sites/aap/aapcms404" failed (2: No such file or directory), client: 127.0.0.1, server: aap.dev, request: "GET /patterns/header/header.html.php?view=preview HTTP/1.1", host: "aap.dev", referrer: "http://aap.dev/patterns/header/header.html.php?view=html"`

Any ideas?

**Comment by dkerzig** [comment]
+1 on fixing this

**Comment by paulrobertlloyd** [comment]
I’m seeing this also… clicking through to issue #31, seems it might be a more substantial issue with PHP. Does it’s internal web server not play nice with nginx?!

**Comment by paulrobertlloyd** [comment]
Whoop! I seem to have fixed this! Turns out it’s a case of adjusting your nginx config ([uncovered after reading the discussion about a similar issue with the Slim framework](https://github.com/slimphp/Slim/issues/1829#issuecomment-202494715)) to include `try_files $uri $uri/ /index.php$is_args$args;`. For example, I changed this…

```
location ~ \.php$ {
  fastcgi_pass 127.0.0.1:9000;
  fastcgi_index index.php;
  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  include fastcgi_params;
}
```

to this…

```
location ~ \.php$ {
  try_files $uri $uri/ /index.php$is_args$args;
  fastcgi_pass 127.0.0.1:9000;
  fastcgi_index index.php;
  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  include fastcgi_params;
}
```

Not entirely sure why this works… I think perhaps there are some arguments added to the URL internally, that nginx needs to know about.

**Comment by paulrobertlloyd** [comment]
(And when I say I have fixed *this*, I mean fixed the nginx issue *I was having*! I wonder if it addresses the issues you’ve been having, @shoesforindustry and @dkerzig?)

**Comment by shoesforindustry** [comment]
Paul, you have been busy :), sorry for the delay in replying, knee deep (literally) in house refurb, so somewhat pre-occupied. Although we have different nginx configs to yourself, I did try the suggested line in the same place, but we still don't seem to get any CSS loading for patterns so it still looks plain text.

**Comment by shoesforindustry** [comment]
Further to the above, I'm stil getting 404's for

`http://aap.dev/patterns/assets/index.css` and `http://aap.dev/patterns/assets/index.js`

**Comment by jvgreenaway** [comment]
I had the issue of `/patterns/assets/index.js` no loading too. It ended up being my nginx config. I had a 'long expire headers' block which was getting in the way. Disabling it fixed my issue.

```
    # location ~* ^.+\.(ico|jpg|gif|png|css|js|svg|eot|ttf|woff|woff2|otf)$ {
    #   log_not_found off;
    #   expires 7d;
    #   etag on;
    # }
```
